[package]
name = "practice"
version = "0.1.0"
edition = "2021"
include = [
  "src/**/*"
]

[dependencies]
rand="0.8.5"
device_query="2.1.0"
regex="1.10.5"
snailquote="0.3.0"

[[bin]]
name = "practice"
path = "src/main.rs"
